# Generated by Django 4.1.5 on 2023-01-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_id_list', models.TextField(max_length=200)),
            ],
        ),
    ]
