# Generated by Django 4.1.5 on 2023-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0003_inputfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(max_length=200),
        ),
    ]
