# Generated by Django 4.1.5 on 2023-01-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0004_alter_product_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(max_length=150),
        ),
    ]
